springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create





#spring.datasource.url: jdbc:h2:mem:testdb
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password:
#spring.jpa.database-platform: org.hibernate.dialect.H2Dialect